### ISSUE TITLE
i am a new use of too good to go

### ISSUE THREAD

**Issue by lesusviya** [marklagendijk/node-toogoodtogo-watcher#109] opened 2021-10-31 14:08 UTC
hello.
i am a new use of too good to go
that mean i only can apply account through email or facebook without password.

it mean i can not use this watcher,
is it possible to solve this question?

**Comment by Zoa-home** [comment] 2021-11-02 16:10
Log to another device, you receive an alert mail to reset password.

**Comment by JohnRambo1993** [comment] 2021-11-03 19:43
I can confirm, this is not possible. You can't reset your password or anything like that.

**Comment by marklagendijk** [comment] 2021-11-03 20:27
@JohnRambo1993 what @Zoa-home means is: 
If you login from another device (or reset the config from the TooGoodToGo app, and login again) you get an email from TooGoodToGo about this.
In this email there is a link to reset your password.

Now it might be that this email isn't sent for new accounts.
In that case the only solution would be to make the new login mechanism work. 

If someone feels like researching this and implementing it, please do. I might never get to it, or it might take a long time.

**Comment by kacpi2442** [comment] 2021-11-03 20:47
You can reset password here: https://store.toogoodtogo.com/reset-password

**Comment by lesusviya** [comment] 2021-11-03 20:51
> You can reset password here: https://store.toogoodtogo.com/reset-password

i am not sure it work or not,
even success to reset password and login,
it show me 


Oops!
Something went wrong...


well.....
i do not think i accept the new account use password anymore

**Comment by kacpi2442** [comment] 2021-11-03 20:54
> > You can reset password here: https://store.toogoodtogo.com/reset-password
> 
> i am not sure it work or not, even success to reset password and login, it show me
> 
> Oops! Something went wrong...
> 
> well..... i do not think i accept the new account use password anymore

I've actually reset my password this way like 10 minutes ago

**Comment by marklagendijk** [comment] 2021-11-03 20:55
@kacpi2442 yes, but it might be that it doesn't work for new accounts.

**Comment by kacpi2442** [comment] 2021-11-03 20:58
> @kacpi2442 yes, but it might be that it doesn't work for new accounts.

It was an account created specifically for this project like half an hour ago

**Comment by lesusviya** [comment] 2021-11-03 20:59
> @kacpi2442 yes, but it might be that it doesn't work for new accounts.

but how you prove it work?
i change my password and login this web
https://store.toogoodtogo.com/login

if failed, it show me

"The email or password did not match. Please try again."


even success, it change place and show me
"
Oops!
Something went wrong...
"
no matter success and failed,
two of them can not work.

**Comment by kacpi2442** [comment] 2021-11-03 21:01
> > @kacpi2442 yes, but it might be that it doesn't work for new accounts.
> 
> but how you prove it work? i change my password and login this web https://store.toogoodtogo.com/login
> 
> if failed, it show me
> 
> "The email or password did not match. Please try again."
> 
> even success, it change place and show me " Oops! Something went wrong... " no matter success and failed, two of them can not work.

You can't log in to web because it's for stores only

**Comment by lesusviya** [comment] 2021-11-03 21:06
> > > @kacpi2442 yes, but it might be that it doesn't work for new accounts.
> > 
> > 
> > but how you prove it work? i change my password and login this web https://store.toogoodtogo.com/login
> > if failed, it show me
> > "The email or password did not match. Please try again."
> > even success, it change place and show me " Oops! Something went wrong... " no matter success and failed, two of them can not work.
> 
> You can't log in to web because it's for stores only

so.....my user account do not have password,
i only can apply account through email or facebook without password.
and my store account can not login and use.

the situation back to my original question.
it mean i can not use this watcher,
is it possible to solve this question?

**Comment by kacpi2442** [comment] 2021-11-03 21:17
> > > > @kacpi2442 yes, but it might be that it doesn't work for new accounts.
> > > 
> > > 
> > > but how you prove it work? i change my password and login this web https://store.toogoodtogo.com/login
> > > if failed, it show me
> > > "The email or password did not match. Please try again."
> > > even success, it change place and show me " Oops! Something went wrong... " no matter success and failed, two of them can not work.
> > 
> > 
> > You can't log in to web because it's for stores only
> 
> so.....my user account do not have password, i only can apply account through email or facebook without password. and my store account can not login and use.
> 
> the situation back to my original question. it mean i can not use this watcher, is it possible to solve this question?
- You put your email address here: https://store.toogoodtogo.com/reset-password
- Wait for e-mail with password reset link
- Set a password
- Put login details in config.json file

**Comment by luisluet** [comment] 2021-11-06 13:04
>     * You put your email address here: https://store.toogoodtogo.com/reset-password
> 
>     * Wait for e-mail with password reset link
> 
>     * Set a password
> 
>     * Put login details in config.json file

Worked completly fine for me with an account created on 6th Nov. 2021

**Comment by sebastianjena** [comment] 2021-11-17 20:04
No mather I do I'm only getting a code to log in... When i enter my email on website it doesnt work

**Comment by marklagendijk** [comment] 2021-12-13 07:11
Can someone try with a new account in combination with the latest version (3.8.0)?

**Comment by sebastianjena** [comment] 2021-12-13 11:40
I tried with my existing account and it works fine to me now

**Comment by marklagendijk** [comment] 2021-12-14 10:42
I'll close this issue. If there are still problems a new issue can be opened.

**Closed by marklagendijk** 2021-12-14 10:42 UTC
Labels: help wanted
