### ISSUE TITLE
Watch command gives error during token refresh request

### ISSUE THREAD

**Issue by JTson8** [marklagendijk/node-toogoodtogo-watcher#201] opened 2023-01-18 09:25 UTC
After I successfully login with "toogoodtogo-watcher login" with the message `You are now successfully logged in!` and then try "toogoodtogo-watcher watch" I immediately get the following:

```
Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
{
    "refresh_token": "..."
}

HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/home/bitnami/.nvm/versions/node/v16.6.2/lib/node_modules/toogoodtogo-watcher/no
de_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

My node version is `v16.6.2`

**Comment by c0lumb0** [comment] 2023-01-18 09:46
Same here.
Seems to be related to these topics, which seem to be IP related topics

https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/192
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/180

**Comment by DzianisMakeichyk** [comment] 2023-01-19 08:16
Doesn't seem to be a problem with `ERR_NON_2XX_3XX_RESPONSE`

**Comment by c0lumb0** [comment] 2023-01-19 12:14
> Doesn't seem to be a problem with `ERR_NON_2XX_3XX_RESPONSE`

True, login seems to work now, but the watch error still pops up as described above.
I reinstalled the application from scratch.

**Comment by c0lumb0** [comment] 2023-01-19 13:29
> you reinstalled and it works?

No, I restinalled from scratch and still geht the error as mentioned. Sry.

**Comment by c0lumb0** [comment] 2023-01-19 13:48
> In my case, I was trying to run the watcher over on AWS. I believe toogoodtogo might actually be banning ip addresses from AWS. I can get the watcher to work on my local server with no problems.

I run the application on a small windows tablet.
When I first got the error, I reinstalled the application from scratch, then it worked for 2 days or so before still getting the error. Now a reinstallation doesn't work anymore :(

Maybe it is really an IP issue?
Other TGTG applications have similar issues but also related to `Datadome `protection...

**Comment by Valmlbr** [comment] 2023-01-21 12:33
I have the same problem here. Seems to be a temp IP ban because when I'm using a VPN, I can use ` toogoodtogo-watcher login` but can't use ` toogoodtogo-watcher watch`...

**Comment by Pazekal90** [comment] 2023-01-21 12:41
Me too :) also have the same problem.

**Comment by affebaffe87** [comment] 2023-01-21 17:04
me too do you have a solution ? :o

**Comment by JTson8** [comment] 2023-01-22 09:33
It does seem to be a datadome issue. 
I have moved on to trying to get this running on my raspberry pi and of course there I have the same issues. I took the failed refresh request from my pi to postman on my local pc. Here, after changing the User-Agent in the headers, the refresh request worked and with it I got a datadome cookie.
I took this cookie and updated my config like so
```
"deviceType": "IOS",
"headers": {
    "Cookie": "datadome=..."
},
"pollingIntervalInMs": 30000,
```
now `toogoodtogo-watcher watch` seems to be working on my pi, but probably only until my datadome cookie expires. Also since datadome cookie is ip specific I could only use it on other devices in my local network. So the same trick did not work on AWS.

I would not say this a solution, just simply the results of my own investigation to this issue.

**Comment by c0lumb0** [comment] 2023-01-22 11:39
> It does seem to be a datadome issue. I have moved on to trying to get this running on my raspberry pi and there I have the same issues. I took the failed refresh request from my pi to postman on my local pc. Here, after changing the User-Agent in the headers, the refresh request worked and with it I got a datadome cookie. I took this cookie and updated my config like so
> 
> ```
> "deviceType": "IOS",
> "headers": {
>     "Cookie": "datadome=..."
> },
> "pollingIntervalInMs": 30000,
> ```
> 
> now `toogoodtogo-watcher watch` seems to be working on my pi, but probably only until my datadome cookie expires. Also since datadome cookie is ip specific I could only use it on other devices in my local network. So the same trick did not work on AWS.
> 
> I would not say this a solution, just simply the results of my own investigation to this issue.

I was just trying the same, but I get no cookie with postman.
Could you tell us how you did that exactly?

**Comment by maarten551** [comment] 2023-01-22 12:02
> I was just trying the same, but I get no cookie with postman. Could you tell us how you did that exactly?

What I did:
1. I went to the following URL in my browser: https://apptoogoodtogo.com/api/auth/v3/token/refresh
2. Opened my developer tools and opened the Network tap
3. Completed the CAPTCHA
4. Checked my last request in the network tab, and copied the '_datadome_' cookie to the config.json

**Comment by c0lumb0** [comment] 2023-01-22 12:44
> > I was just trying the same, but I get no cookie with postman. Could you tell us how you did that exactly?
> 
> What I did:
> 
>     1. I went to the following URL in my browser: https://apptoogoodtogo.com/api/auth/v3/token/refresh
> 
>     2. Opened my developer tools and opened the Network tap
> 
>     3. Completed the CAPTCHA
> 
>     4. Checked my last request in the network tab, and copied the '_datadome_' cookie to the config.json
> 
>     5. Restart the watcher
> 
>     6. Profit (No idea for how long)
> 
> 
> Edit: It worked for a small bit, but it now gives errors again at the refresh 🤔 (even if I update the cookie)

Wow, that worked just fine tbh, although I did not get any captcha in the browser since I did the captcha in the app once not too long ago but with the same IP as now, so it should be fine for this IP.
For the validity part, I found a parameter in the network tab of the browser (Max-Age=31536000) along with other ones like (Domain=.apptoogoodtogo.com), so maybe this one is the validity of the datadome cookie in MS?

**Comment by Pazekal90** [comment] 2023-01-22 14:47
Doesn't work for me :/ Sorry

**Comment by DzianisMakeichyk** [comment] 2023-01-25 08:24
Does it work for somebody?

**Comment by c0lumb0** [comment] 2023-01-25 08:29
> Does it work for somebody?

Yup, it works for me for some days now.
Although postman did not get me a datadome cookie, opening the refreshing token request in the browser, with solving the captcha did and then I added the cookie as described:

`"deviceType": "IOS",
"headers": {
    "Cookie": "datadome=..."
},
"pollingIntervalInMs": 30000,`

**Comment by DzianisMakeichyk** [comment] 2023-01-25 09:08
> > Does it work for somebody?
> 
> Yup, it works for me for some days now. Although postman did not get me a datadome cookie, opening the refreshing token request in the browser, with solving the captcha did and then I added the cookie as described:
> 
> `"deviceType": "IOS", "headers": { "Cookie": "datadome=..." }, "pollingIntervalInMs": 30000,`

I did the same, but still `403` 🤔

**Comment by linict** [comment] 2023-02-03 21:30
I can confirm that adding the datadome cookie to the config file has resolved this issue for me.

**Comment by Karantas** [comment] 2023-02-14 23:20
> > I was just trying the same, but I get no cookie with postman. Could you tell us how you did that exactly?
> 
> What I did:
> 
>     1. I went to the following URL in my browser: https://apptoogoodtogo.com/api/auth/v3/token/refresh
> 



This URL just returns me a 405. 
_Failed to load resource: the server responded with a status of 405 ()_

What am I doing wrong?

**Comment by c0lumb0** [comment] 2023-02-16 06:17
> > > I was just trying the same, but I get no cookie with postman. Could you tell us how you did that exactly?
> > 
> > 
> > What I did:
> > ```
> > 1. I went to the following URL in my browser: https://apptoogoodtogo.com/api/auth/v3/token/refresh
> > ```
> 
> This URL just returns me a 405. _Failed to load resource: the server responded with a status of 405 ()_
> 
> What am I doing wrong?

Please see https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/212#issuecomment-1431987652 for that.

**Comment by marklagendijk** [comment] 2023-02-28 19:15
I expect that all issues with this are now fixed, except for the case where datadome asks to solve a CAPTCHA.
If this is not the case, let me know.

**Closed by marklagendijk** 2023-02-28 19:15 UTC
