### ISSUE TITLE
Can be limited only to my telegram user?

### ISSUE THREAD

**Issue by dferrandizmont** [marklagendijk/node-toogoodtogo-watcher#195] opened 2022-11-22 15:32 UTC
I'd like to know if the bot can be limited to only answer to my `chatId`. As the bot is public, can be somehow limited?

Thank you.

**Comment by c0lumb0** [comment] 2022-11-24 05:40
Good question...I just stopped sharing the bot since the config menu in Telegram was implemented.

**Comment by marklagendijk** [comment] 2023-01-25 19:44
Duplicate of #178

**Closed by marklagendijk** 2023-01-25 19:44 UTC
