### ISSUE TITLE
Issues running Docker container on Heroku

### ISSUE THREAD

**Issue by cswpy** [marklagendijk/node-toogoodtogo-watcher#97] opened 2021-09-15 05:22 UTC
I encountered issues when trying to run `node index.js watch` on the container pulled from docker hub on Heroku. I tagged the image pulled from the repo and tagged it according to the Heroku [tutorial](https://devcenter.heroku.com/articles/container-registry-and-runtime#building-and-pushing-image-s). 

```
~ $ node index.js watch
undefined:1
{api:{credentials:{email:a@bc.com,password:rly-good-password},session:{},headers:{User-Agent:TooGoodToGo/20.6.1 (813) (iPhone/iPhone 7 (GSM); iOS 13.6; Scale/2.00)},pollingIntervalInMs:30000,authenticationIntervalInMS:3600000},notifications:{console:{enabled:false,clear:true},desktop:{enabled:false},telegram:{enabled:true,botToken:some-amazing-token,chats:[]},ifttt:{enabled:false,webhookKey:see README,webhookEvents:[see README]},gotify:{enabled:false,url:http://push.example.com,apptoken:token,priority:5}},messageFilter:{showUnchanged:false,showDecrease:false,showDecreaseToZero:false,showIncrease:false,showIncreaseFromZero:true}}
 ^

SyntaxError: Unexpected token a in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/app/index.js:36:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

I am not sure running dockerized node app on Heroku is the best option. But I tried to launch a worker using Procfile on Heroku directly also failed. Could you provide more detailed instructions on deploying on Heroku if possible?

**Comment by marklagendijk** [comment] 2021-11-03 18:18
It looks like the quotes of your JSON are being stripped out. Maybe you need to escape them in a certain way?

**Comment by marklagendijk** [comment] 2021-11-03 20:28
Duplicate of #67.

**Closed by marklagendijk** 2021-11-03 20:28 UTC
